mysite/home/urls.py
from django.urls import path
from . import views
""" from snipcartwagtaildemo.home.views import canjear
from mysite.snipcartwagtaildemo.home import views as views_tienda """

# import snipcartwagtaildemo.home.views

urlpatterns = [
    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('tienda/', views.tienda, name='tienda'),
    path('saldo/<int:id_user>/<int:saldo>/', views.saldo, name='saldo'),
    #path('/<int:id>/canjear', canjear)
    # path('<int:page_ptr_id>/canjear/', snipcartwagtaildemo.home.views.canjear, name='canjear'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.urls import path, re_path, include
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

#Desde aca se definen los url, se combierten los datos tomados del url a enteros ya que los datos sacados del url se obtienen como string

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/home/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    valor_market_balance = models.BigIntegerField(default=0)

mysite/polls/models.py
from django.db import models

import datetime
from django.db import models
from django.utils import timezone
from django.db import models

from django.contrib.auth.models import User

#Definimos las preguntas

class Question(models.Model):
    completed_by = models.ManyToManyField(User, null=True, blank=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Fecha publicación')
    ValorMarket = models.IntegerField('Monedas')
    #Ver como hacer que se cree la columna por base de datos, lo hice usando el DBLite
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

#Definimos las respuestas que estarán asociadas a las preguntas
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    Saldo = models.IntegerField('Monedas')
    def __str__(self):
        return self.choice_text

mysite/snipcartwagtaildemo/home/models.py
from django.db import models
#from django import HttpResponse
from modelcluster.fields import ParentalKey
from wagtail.core.models import Page, Orderable
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.core.models import Page
from wagtail.core.fields import RichTextField

# Definición del Home de la tienda

class HomePage(Page):
    def get_context(self, request):
        context = super().get_context(request)

        context['products'] = Product.objects.child_of(self).live()

        return context

# Definición de productos de la tienda

class Product(Page):
    sku = models.CharField(max_length=255)
    short_description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+')

    content_panels = Page.content_panels + [
        FieldPanel('sku'),
        FieldPanel('price'),
        ImageChooserPanel('image'),
        FieldPanel('short_description'),
        InlinePanel('custom_fields', label='Custom fields'),
        ]

    def get_context(self, request):
        context = super().get_context(request)
        fields = []
        for f in self.custom_fields.get_object_list():
            if f.options:
                f.options_array = f.options.split('|')
                fields.append(f)
            else:
                fields.append(f)

        context['custom_fields'] = fields

        return context

# Definición de campos adicionales del producto

class ProductCustomField(Orderable):
    product = ParentalKey(Product, on_delete=models.CASCADE, related_name='custom_fields')
    name = models.CharField(max_length=255)
    options = models.CharField(max_length=500, null=True, blank=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('options')
        ]


from wagtail.contrib.settings.models import BaseSetting, register_setting


#def canjear(request, id):
#    precioproducto = price
#    monto = ("%s", price)
#    return HttpResponse(monto)

@register_setting
class SnipcartSettings(BaseSetting):
    api_key = models.CharField(
        max_length=255,
        help_text='Your Snipcart public API key'
        )

mysite/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    birth_date = forms.DateField(required=False, help_text='Optional.')


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birth_date', 'password1', 'password2', )

mysite/home/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User

from home.models import UserProfile
from home.forms import SignUpForm

def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request.POST)
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('home')
            return redirect ('login')
        else:
            form = AuthenticationForm()
        return render(request, 'polls/home.html', {'form': form})
    else:
        return redirect('home')

def home(request):
    if request.user.is_authenticated:
        user_profile, created = UserProfile.objects.get_or_create(
            user_id=request.user.pk
        )
        request.session['saldo'] = user_profile.valor_market_balance
        
        return render(request, 'polls/Dev-uy.html')
    else:
        return redirect('login')
    

def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                auth_login(request, user)
                return redirect('home')
        else:
            form = SignUpForm()
        return render(request, 'home/signup.html', {'form': form})
    else:
        return redirect('home')

def logout(request):
    auth_logout(request)
    return redirect('login')

def tienda(request):
    userProf, created = UserProfile.objects.get_or_create(user_id=request.user.id)
    saldo = userProf.valor_market_balance
    #esto es para probar comprar cosas
    #saldo = 1000
    saldo_str = str(saldo)
    user_id = request.user.id
    id_str = str(user_id)
    new_port='8080'
    hostname = request.get_host().split(':')[0]
    url = 'http://' + hostname + ':' + new_port + '/guardar/' + id_str + '/' + saldo_str + '/'
    return redirect(url)

def saldo(request, id_user, saldo):
    user = get_object_or_404(User, id=id_user)
    auth_login(request, user)
    
    userProf, created = UserProfile.objects.get_or_create(user_id=id_user)
    userProf.valor_market_balance = saldo

    return redirect('home')

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Choice, Question
from django.http import Http404
from django.views import generic

from home.models import UserProfile

# Prueba de respuesta de votacion
# def vote(request, question_id):
#    return HttpResponse("You're voting on question %s." % question_id)

#Tomamos el Id de la pregunta
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'encuestas/detail.html', {
            'question': question,
            'error_message': "No seleccionaste una opción"
        })
    else:
        #Sumamos el voto a la pregunta seleccionada
        selected_choice.votes += 1
        selected_choice.Saldo += question.ValorMarket
        # Lo que hace esto es sumarle el valor del market a la columna de la respuesta, pero precisamos la forma de tener
        # un saldo que sea unico, probar una variable que se sume con ValorMarket o algo así
        selected_choice.save()

        # Lo que hace esto es registrar que la pregunta elegida fue completada por el usuario logueado
        question.completed_by.add(request.user)
        question.save()

        # Se incrementa el saldo del usuario de acuerdo a las monedas de la pregunta
        user_profile, created = UserProfile.objects.get_or_create(
            user_id=request.user.pk
        )
        user_profile.valor_market_balance += question.ValorMarket
        user_profile.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class IndexView(generic.ListView):
    template_name = 'encuestas/index.html'
    context_object_name = 'latest_question_list'
    # Modelo generico sacado del tutorial de Django

    def get_queryset(self):
        enabled_questions = Question.objects.exclude(
            completed_by__pk=self.request.user.pk).order_by('-pub_date')[:5]
        disabled_questions = Question.objects.filter(
            completed_by__pk=self.request.user.pk).order_by('-pub_date')[:5]

        return {'enabled_questions': enabled_questions, 'disabled_questions': disabled_questions}


class DetailView(generic.DetailView):
    model = Question
    template_name = 'encuestas/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'encuestas/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = UserProfile.objects.get(user_id = self.request.user.pk)
        context['valor_market_balance'] = user_profile.valor_market_balance
        return context
    

mysite/snipcartwagtaildemo/home/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from home.models import Product
from django.urls import reverse

#Canjear toma el id del producto del url

def canjear(request, page_ptr_id):
    producto = get_object_or_404(Product, pk=page_ptr_id)

    # Se resta el saldo del usuario
    """ user_profile, created = UserProfile.objects.get_or_create(
        user_id=request.user.pk
    )
    user_profile.valor_market_balance =- home.models.Product.price
    user_profile.save() """

    saldoActual = int(request.session['saldo'])
    
    if (saldoActual >= producto.price):
        saldoActual = int(saldoActual - producto.price)

        request.session['saldo'] = str(saldoActual)
        request.session['canjeado'] = True
    else:
        request.session['canjeado'] = False
        
    request.session['alert'] = 0
        
    

    new_port='8080'
    hostname = request.get_host().split(':')[0]
    url = 'http://' + hostname + ':' + new_port + '/'
    return redirect(url)


    #return HttpResponseRedirect(reverse('polls:results', args=(page_ptr_id,)))
    

def guardar_saldo(request, id, saldo):
    request.session['saldo'] = saldo
    request.session['id'] = id
    new_port='8080'
    hostname = request.get_host().split(':')[0]
    url = 'http://' + hostname + ':' + new_port + '/'
    return redirect(url)

def home(request):
    request.session['alert'] = 1
    saldo = request.session['saldo']
    saldo_str = str(saldo)
    user_id = request.session['id']
    id_str = str(user_id)
    new_port='8000'
    hostname = request.get_host().split(':')[0]
    url = 'http://' + hostname + ':' + new_port + '/saldo/' + id_str + '/' + saldo_str + '/'
    return redirect(url)

mysite/home/templates/polls/Dev-uy.html
<!doctype html>

{% load static %}


<html lang="es">
  <head>
    <title>Proyecto Dev.uy Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    * {
        box-sizing: border-box;
    }
    .w3-sidebar a {font-family: "Roboto", sans-serif}
    body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
  </head>
  <body class="w3-content" style="max-width:1200px">

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
      <div class="w3-container w3-display-container w3-padding-16">
        <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
        <img src='{% static "mysite/img/logo_devuy.png" %}' alt="Dev.uy Logo" style="width:100%">
        <h3 class="w3-wide"><b>Mi Tienda</b></h3>
      </div>
      <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
        <a href="{% url 'home' %}" class="w3-bar-item w3-button">Home</a>
        <a href="{% url 'tienda' %}" class="w3-bar-item w3-button">Tienda</a>
        <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
          Perfil <i class="fa fa-caret-down"></i>
        </a>
     <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
         <a href="#" class="w3-bar-item w3-button w3-light-grey"><img src='{% static "mysite/img/Icono_perfil.png" %}' class="fa fa-caret-right w3-margin-right" style="width: 100%"></a>
         <a href="#" class="w3-bar-item w3-button">{{ user.username }}</a>
         <a href="{% url 'logout' %}" class="w3-bar-item w3-button">Logout</a>
         
         <a href="#" class="w3-bar-item w3-button">Créditos:  </a>
         <!-- <a href="#" class="w3-bar-item w3-button">Créditos: </a>
         <a href="#" class="w3-bar-item w3-button">Encuestas Respondidas:0</a> -->
     </div>
        <!-- <a href="#" class="w3-bar-item w3-button"></a>
        <a href="#" class="w3-bar-item w3-button"></a>
        <a href="#" class="w3-bar-item w3-button"></a>
        <a href="#" class="w3-bar-item w3-button"></a> -->
     </div>
  <!-- Footer opcional para más información sobre los usuarios <a href="#footer" class="w3-bar-item w3-button w3-padding"></a>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding" onclick="document.getElementById('newsletter').style.display='block'">Otros aspectos de interés sobre los usuarios</a>
  <a href="#footer"  class="w3-bar-item w3-button w3-padding"></a-->

   </nav>

<!-- Top menu on small screens -->

   <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
      <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
   </header>

<!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
    <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
    <header class="w3-container w3-xlarge">
       <!--  <p class="w3-left">Destacados</p> -->
        <p class="w3-right">
            <i class="fa fa-shopping-cart w3-margin-right"></i>
            <i class="fa fa-search"></i>
        </p>
   </header>

  <!-- Image header -->
      <div class="w3-display-container w3-container">
    <!--     <img src='{% static "mysite/img/invierno.jpg" %}' alt="Invierno" style="width:100%"> -->
        <!--img src="img/ropa3.jpg" alt="Jean" style="width:50%"-->
          <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
            <h1 class="w3-jumbo" style="color: black position: absolute">NUEVA COLECCIÓN</h1>
            <h1 class="w3-hide-large w3-hide-medium 3w-black" style="color: black position: absolute">NUEVA COLECCIÓN</h1>
            <h1 class="w3-hide-small">Invierno 2020</h1>
            <div class="w3-button " style="margin-right:200px">
                <p><a href="" class="w3-button  w3-black w3-padding-large w3-large" style="">COMPRAR AHORA</a></p>
            </div>
          </div>
      </div>

      <div class="w3-container w3-text-grey" id="">

        <!--Párrafo opcional p></p-->

      </div>

      <!-- Product grid -->
      <div class="w3-row w3-grayscale">
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <!--img src="/w3images/jeans1.jpg" style="width:100%"-->
            <p><br><b></b></p>
          </div>
          <div class="w3-container">
            <!--img src="img/ropa2.jpg" style="width:100%"-->
            <p><br><b></b></p>
          </div>
       </div>

        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <!--img src="/w3images/jeans2.jpg" style="width:100%"-->
              <!--Para habilitar con las imágenes span class="w3-tag w3-display-topleft"></span-->
              <div class="w3-display-middle w3-display-hover">
                <button class="w3-button w3-black">¡Comprar Ahora! <i class="fa fa-shopping-cart"></i></button>
              </div>
            </div>
            <p><br><b></b></p>
          </div>
          <div class="w3-container">
            <!--img src="/w3images/jeans3.jpg" style="width:100%"-->
            <p><br><b></b></p>
          </div>
        </div>

        <div class="w3-col l3 s6">
          <div class="w3-container">
            <!--img src="/w3images/jeans3.jpg" style="width:100%"-->
            <p><br><b></b></p>
          </div>
          <div class="w3-container">
            <div class="w3-display-container">
              <!--img src="img/ropa3.jpg" style="width:100%"-->
              <!--Para habilitar con las imágenes span class="w3-tag w3-display-topleft">Comprar</span-->
              <div class="w3-display-middle w3-display-hover">
                <button class="w3-button w3-black">Comprar Ahora <i class="fa fa-shopping-cart"></i></button>
              </div>
            </div>
            <p><br><b class="w3-text-red"><b></p>
          </div>
        </div>

        <!-- <div class="w3-col l3 s6">
          <div class="w3-container">
            <img src='{% static "mysite/img/ropa2.jpg" %}' style="width:100%">
            <p>Artículo<br><b>Créditos</b></p>
          </div>
          <div class="w3-container">
            img src="/w3images/jeans1.jpg" style="width:100%"
            <p>Artículo<br><b>Créditos</b></p>
          </div>
        </div>
      </div> -->

  <!-- Subscribe section -->
      <div class="w3-container w3-black w3-padding-32">
        <h1>Danos tu opinión</h1>
        <p>Para ganar créditos y obtener muchos premios</p>
        <!-- <p><input class="w3-input w3-border" type="text" placeholder="Lista de Encuestas" style="width:100%"></p> -->
        <a type="button" role="button" href="/polls" class="w3-button w3-red w3-margin-bottom">ENCUESTAME</a>
      </div>

  <!-- Footer -->
      <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
        <div class="w3-row-padding" style="padding-right: 30px;">
          <div class="w3-col s4">
            <h4>Contacto</h4>
            <p>¿Preguntas o Sugerencias?</p>
            <form action="/action_page.php" target="_blank">
              <p><input class="w3-input w3-border" type="text" placeholder="Nombre" name="Name" required></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Asunto" name="Subject" required></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Mensaje" name="Message" required></p>
              <button type="submit" class="w3-button w3-block w3-black">Enviar</button>
            </form>
          </div>

      <div class="w3-col s4">
        <h4>Acerca de</h4>
        <p><a href="#">Acerca de Nosotros</a></p>
        <p><a href="#">Novedades</a></p>
        <p><a href="#">Promociones</a></p>
        <p><a href="#">Ayuda</a></p>
        <p><a href="#"></a></p>
        <p><a href="#"></a></p>
        <p><a href="#"></a></p>
        <p><a href="#"></a></p>
        <p><a href="#"></a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>La Empresa</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Ubicación</p>
        <p><i class="fa fa-fw fa-phone"></i> 0000123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4></h4>

        <!--LOGOS FORMA DE PAGO desactivados p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p-->
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24 w3-hover-opacity">Dev.uy <!--Insertar link de nuestro dominio a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a--></div>

  <!-- End page content -->
  </div>

<!-- Newsletter Modal -->
    <div id="newsletter" class="w3-modal">
      <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
        <div class="w3-container w3-white w3-center">
          <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
          <!--h2 class="w3-wide">NEWSLETTER</h2>
          <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
          <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p-->
          <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
        </div>
      </div>
    </div>

    <script>
    // Accordion
    function myAccFunc() {
      var x = document.getElementById("demoAcc");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }

    // Click on the "Jeans" link on page load to open the accordion for demo purposes
    document.getElementById("myBtn").click();


    // Open and close sidebar
    function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
      document.getElementById("myOverlay").style.display = "block";
    }

    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
      document.getElementById("myOverlay").style.display = "none";
    }
    </script>

    </body>
</html>

mysite/home/templates/polls/detail.html
<!DOCTYPE html>
    <head>
        <title>Tienda Template</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src=”prefix.js”></script>
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style >

        * {  margin: 0;
             padding: 0;
             box-sizing: border-box;
        }
        </style>
    </head>

    <body>
        <header>
            <nav>
                <ul class="nav">
                  <li>
                    <a href="home.html">Iniciar Sesión</a>
                  </li>
                  <li>
                    <a href="tienda.html">La Tienda</a>
                    <ul>
                        <li><a href="Dev-uy.html">Mi Tienda</a>
                        </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#">Contacto</a>
                  </li>
                </ul>
            <nav>
        </header>
        {% if request.user.is_authenticated %}
            <h1>{{ question.question_text }}</h1>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Votar">
            </form>
        {% else %}
            <h2>Error: Para responder encuestas debe iniciar sesion.</h2>
        {% endif %}

    </body>
    <footer>
        <div class="newsletter">Dev.uy <!--Insertar link de nuestro dominio a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a--></div>
    </footer>
</html>

mysite/home/templates/polls/results.html
<!DOCTYPE html>
{% if request.user.is_authenticated %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{choice.votes}} votos{{ hoice.votes|pluralize}}</li>
    {% endfor %}
    </ul>

{% else %}
    <h2>Error: Para responder encuestas debe iniciar sesion.</h2>
{% endif %}

<p>Felicitaciones, has ganado {{ question.ValorMarket }} monedas.</p>
<p>En total tienes {{ valor_market_balance }} monedas para canjear por premios en nuestra tienda.</p>

<a href="{% url 'polls:index' %}">¿Votar de nuevo?</a>